<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <WarnOn>3390;$(WarnOn)</WarnOn>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Topic.fs" />
        <Compile Include="Post.fs" />
        <Compile Include="Services\IPostService.fs" />
        <Compile Include="Services\PostService.fs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Markdig" Version="0.37.0" />
      <PackageReference Include="YamlDotNet" Version="15.1.6" />
    </ItemGroup>

</Project>
